# window dimensions
window:
   columns: 0
   lines: 0

# window position
position:
   x: 0
   y: 0

# window padding
padding:
   x: 3
   y: 3

# window decorations
decorations: none

# window start mode
startup_mode: Maximized

# window title
title: terminal

# scrollback buffer value
scrolling:
 history: 20000


# font config
font:
 # normal font face
 normal:
   # font family
   family: monospace

   style: Regular

 # bold font face
 bold:
   # font family
   family: monospace

   style: Bold

 # italic font face
 italic:
   # font family
   family: monospace

   style: Italic

 # bold italic font face
 bold_italic:
   # font family
   family: monospace

   style: Bold Italic

 # Point size
 size: 9.0

 # offset space around each char
 offset:
   x: 1
   y: 1

# color config
colors:
 # default colors
 primary:
   background: '#060606'
   foreground: '#cccccc'

 # cursor colors
 cursor:
   text: '#060606'
   cursor: '#cccccc'

 # selection colors
 selection:
   text: '#060606'
   background: '#cccccc'

 # normal colors
 normal:
   black:   '#090909'
   red:     '#cc0303'
   green:   '#909090'
   yellow:  '#e0e000' 
   blue:    '#eeeeee'
   magenta: '#6000E0'
   cyan:    '#003040'
   white:   '#303030'

 # bright colors
 bright:
   black:   '#030303'
   red:     '#cc0303'
   green:   '#909090'
   yellow:  '#e0e000' 
   blue:    '#eeeeee'
   magenta: '#6000E0'
   cyan:    '#003040'
   white:   '#aaaaaa'

