 #________________________________________________ 
 # ______  ______  ____   _    ____  _____  _____   
 #|      >|   ___||    \ | |  |    ||_    ||     |  
 #|     < |   ___||     \| | _|    | |    ||     \  
 #|______>|______||__/\____||______| |____||__|\__\                                                   
 #_________________________________________________



# window dimensions
window:
   columns: 0
   lines: 0

# window position
position:
   x: 0
   y: 0

# window padding
padding:
   x: 3
   y: 3

# window decorations
decorations: none

# window start mode
startup_mode: Maximized

# window title
title: terminal

# scrollback buffer value
scrolling:
 history: 20000


# font config
font:
 # normal font face
 normal:
   # font family
   family: monospace

   style: Regular

 # bold font face
 bold:
   # font family
   family: monospace

   style: Bold

 # italic font face
 italic:
   # font family
   family: monospace

   style: Italic

 # bold italic font face
 bold_italic:
   # font family
   family: monospace

   style: Bold Italic

 # Point size
 size: 9.0

 # offset space around each char
 offset:
   x: 1
   y: 1

# color config
colors:
 # default colors
 primary:
   background: '#0e1111'
   foreground: '#808080'

 # cursor colors
 cursor:
   text: '#0e1111'
   cursor: '#808080'

 # selection colors
 selection:
   text: '#0e1111'
   background: '#808080'

 # normal colors
 normal:
   black:   '#0e1111'
   red:     '#b6403a'
   green:   '#9999aa'
   yellow:  '#ffff00' 
   blue:    '#778899'
   magenta: '#B3ACE2'
   cyan:    '#c6c8d1'
   white:   '#ffffff'

 # bright colors
 bright:
   black:   '#6b7089'
   red:     '#c2c4ce'
   green:   '#95c4ce'
   yellow:  '#e9b189'
   blue:    '#91acd1'
   magenta: '#ada0d3'
   cyan:    '#95c4ce'
   white:   '#d2d4de'

